<nav class="navbar-foot">
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=shop">Vitrine</a></li>
        <li><a href="index.php?route=account">Mon compte</a></li>
        <li><a href="index.php?route=dashboard">Panneau de control</a></li>
        <li><a href="index.php?route=contact">Contactez-moi</a></li>
        <li><a href="index.php?route=register">Créer un compte</a></li>
        <li><a href="index.php?route=about">À propos</a></li>
        <li><a href="index.php?route=disconnect">Se déconnecter</a></li>
    </ul>
</nav>
<nav class="contact-foot">
    <ul>
        <li><a href="https://github.com/kodingcore" target="_blank"><i class="fa-brands fa-github" style="color: #c55a11;"></i> Github</a></li>
        <li><a href="https://linkedin.com/in/kodingcore" target="_blank"><i class="fa-brands fa-linkedin" style="color: #c55a11;"></i> LinkedIn</a></li>
        <li><i class="fa-solid fa-at" style="color: #c55a11;"></i><a href="mailto:kodingcore@gmail.com">Envoyer un e-mail</a></li>
        <a href="index.php?route=gnu">Politique de confidentialité</a>
    </ul>   
</nav>