<?php
    $userManager = new UserManager();
    $messageManager = new MessageManager();
    $reviewManager = new ReviewManager();
    $infoManager = new InfoManager();
    $templateManager = new TemplateManager();
    // $quotationManager = new QuotationManager();
    // $imageManager = new ImageManager();
    // $categoryManager = new CategoryManager();
    // $appointmentManager = new AppointmentManager();
?>

<aside class="left-pannel">
    <ul>
        <li>
            <a href="#" id="users-link">Users</a>
            <a href="#" id="messages-link">Messages</a>
            <a href="#" id="templates-link">Templates</a>
            <a href="#" id="reviews-link">Reviews</a>
        </li>
    </ul>
</aside>
<main class="container">
    <label for="data-selection">Rechercher par :</label>
    <select name="data-selection" id="data-selection"></select>
    <label for="searchbar">Valeur :</label> 
    <input id="searchbar" type="text" name="searchbar" placeholder="Search..">
    <section id="users-section" class="hidden">
        <h2>Panneau de control des utilisateurs</h2>
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Téléphone</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody id="users-body">
                <?php
                if($userManager->getUsers())
                {
                    $i = 0;
                    foreach($userManager->getUsers() as $user)
                    {   
                        $info = $infoManager->getInfoByUserId($user->getUserId());
                ?>
                    <tr>
                        <td><a href="#" id="user <?=$i;?>"><?=$i;?></a></td>
                        <td><?=$user->getUsername();?></td>
                        <td><?=$user->getEmail();?></td>
                        <td><?=$info->getFirstName();?></td>
                        <td><?=$info->getLastName();?></td>
                        <td><?=$info->getTel();?></td>
                        <td><?=$user->getRole();?></td>
                    </tr>
                <?php
                    $i++;
                    }
                }
                ?>
            </tbody>
        </table>
    </section>
    <section id="messages-section" class="hidden">
        <h2>Panneau de control des messages</h2>
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Username</th>
                    <th>Sujet</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody id="messages-body">
                <?php
                if($messageManager->getMessagesOrderedByDate())
                {
                    $i = 0;
                    foreach($messageManager->getMessagesOrderedByDate() as $message)
                    {   
                        $user = $userManager->getUserByUserId($message->getUserId());
                        $username = $user->getUsername();
                ?>
                    <tr>
                        <td><a href="#" id="message <?=$i;?>"><?=$i;?></a></td>
                        <td><?=$user->getUsername();?></td>
                        <td><?=$message->getSubject();?></td>
                        <td><?=$message->getSendDate();?></td>
                    </tr>
                <?php
                    $i++;
                    }
                }
                ?>
            </tbody>
        </table>
    </section>
    <section id="templates-section" class="hidden">
        <h2>Panneau de control des templates</h2>
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Nom</th>
                    <th>Catégorie</th>
                    <th>Date de création</th>
                    <th>Date de mise à jour</th>
                </tr>
            </thead>
            <tbody id="templates-body">
                <?php
                if($templateManager->getTemplatesOrderedByCreationDate())
                {
                    $i = 0;
                    foreach($templateManager->getTemplatesOrderedByCreationDate() as $template)
                    {   
                        $category = $categoryManager->getCategoryByCategoryId($template->getCategoryId());
                ?>
                    <tr>
                        <td><a href="#" id="template <?=$i;?>"><?=$i;?></a></td>
                        <td><?=$template->getName();?></td>
                        <td><?=$template->getDescription();?></td>
                        <td><?=$template->getCreatedAt();?></td>
                        <td><?=$template->getUpdatedAt();?></td>
                    </tr>
                <?php
                    $i++;
                    }
                }
                ?>
            </tbody>
        </table>
    </section>
    <section id="reviews-section" class="hidden">
        <h2>Panneau de control des reviews</h2>
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Username</th>
                    <th>Sujet</th>
                    <th>Date de création</th>
                </tr>
            </thead>
            <tbody id="reviews-body">
                <?php
                if($messageManager->getMessagesOrderedByDate())
                {
                    $i = 0;
                    foreach($messageManager->getMessagesOrderedByDate() as $message)
                    {   
                        $user = $userManager->getUserByUserId($message->getUserId());
                        $username = $user->getUsername();
                ?>
                    <tr>
                        <td><a href="#" id="message <?=$i;?>"><?=$i;?></a></td>
                        <td><?=$user->getUsername();?></td>
                        <td><?=$message->getSubject();?></td>
                        <td><?=$message->getSendDate();?></td>
                    </tr>
                <?php
                    $i++;
                    }
                }
                ?>
            </tbody>
        </table>
    </section>
    
</main>
<script type="module" src="assets/js/dashboard.js"></script>