<?php
    $userManager = new UserManager();
    $messageManager = new MessageManager();
    $reviewManager = new ReviewManager();
    $infoManager = new InfoManager();
    $templateManager = new TemplateManager();
    // $quotationManager = new QuotationManager();
    // $imageManager = new ImageManager();
    // $categoryManager = new CategoryManager();
    // $appointmentManager = new AppointmentManager();
?>
<!-- ------------------------------------------------------------------------------------- -->
<!-- ----------------PANNEAU GAUCHE DES LIENS VERS LES TABLES DE CONTROL------------------ -->
<!-- ------------------------------------------------------------------------------------- -->
<aside class="left-pannel">
    <ul>
        <li>
            <a href="#" id="users-link">Users</a>
            <a href="#" id="messages-link">Messages</a>
            <a href="#" id="templates-link">Templates</a>
            <a href="#" id="reviews-link">Reviews</a>
        </li>
    </ul>
</aside>

<!-- ------------------------------------------------------------------------------------- -->
<!-- --------------------------------PARTIE PRINCIPALE(VIEW)------------------------------ -->
<!-- ------------------------------------------------------------------------------------- -->
<main class="container">

    <!-- --------------------------- -->
    <!-- ----SECTION DE RECHERCHE--- -->
    <!-- --------------------------- -->
    <section id="search">
        <label for="column-selection">Rechercher par :</label>
        <select name="column-selection" id="column-selection"></select>
        <label for="searchbar">Valeur :</label> 
        <input id="searchbar" type="text" name="searchbar" placeholder="Search..">
    </section>
    
    <!-- --------------------------- -->
    <!-- ---SECTION UTILISATEURS---- -->
    <!-- --------------------------- -->
    <section id="users" class="hidden">
        <h2>Panneau de control des utilisateurs</h2>
        <section id="users-view">
            <h3>Listing users</h3>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Prénom</th>
                        <th>Nom</th>
                        <th>Téléphone</th>
                        <th>Role</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    if($userManager->getUsers())
                    {
                        $i = 0;
                        foreach($userManager->getUsers() as $user)
                        {   
                            $info = $infoManager->getInfoByUserId($user->getUserId());
                    ?>
                        <tr>
                            <td class="data"><button class="row-btn" id="<?=$user->getUserId();?>"><?=$user->getUserId();?></button></td>
                            <td class="data"><?=$user->getUsername();?></td>
                            <td class="data"><?=$user->getEmail();?></td>
                            <td class="data"><?=$info->getFirstName();?></td>
                            <td class="data"><?=$info->getLastName();?></td>
                            <td class="data"><?=$info->getTel();?></td>
                            <td class="data"><?=$user->getRole();?></td>
                        </tr>
                        <?php
                            $i++;
                        }
                    }
                    ?>
                </tbody>
            </table>
        </section>
    </section>           
    <!-- --------------------------- -->
    <!-- ------SECTION MESSAGES----- -->
    <!-- --------------------------- -->
    <section id="messages" class="hidden">
        <h2>Panneau de control des messages</h2>
        <section id="users-view">
            <h3>Listing messages</h3>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Username</th>
                        <th>Sujet</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody id="messages-body">
                    <?php
                    if($messageManager->getMessagesOrderedByDate())
                    {
                        foreach($messageManager->getMessagesOrderedByDate() as $message)
                        {   
                            $user = $userManager->getUserByUserId($message->getUserId());
                            $username = $user->getUsername();
                    ?>
                        <tr>
                            <td class="data"><button class="row-btn" id="<?=$message->getMessageId();?>"><?=$message->getMessageId();?></button></td>
                            <td class="data"><?=$user->getUsername();?></td>
                            <td class="data"><?=$message->getSubject();?></td>
                            <td class="data"><?=$message->getSendDateTime();?></td>
                        </tr>
                    <?php
                        }
                    }
                    ?>
                </tbody>
            </table>
        </section>
    </section>

    <!-- --------------------------- -->
    <!-- -----SECTION TEMPLATES----- -->
    <!-- --------------------------- -->
    <section id="templates" class="hidden">
        <h2>Panneau de control des templates</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Catégorie</th>
                    <th>Date de création</th>
                    <th>Date de mise à jour</th>
                </tr>
            </thead>
            <tbody id="templates-body">
                <?php
                if($templateManager->getTemplatesOrderedByCreationDate())
                {
                    foreach($templateManager->getTemplatesOrderedByCreationDate() as $template)
                    {   
                        $category = $categoryManager->getCategoryByCategoryId($template->getCategoryId());
                ?>
                    <tr>
                        <td class="data"><button class="row-btn" id="<?=$template->getTemplateId();?>"><?=$template->getTemplateId();?></button></td>
                        <td class="data"><?=$template->getName();?></td>
                        <td class="data"><?=$template->getDescription();?></td>
                        <td class="data"><?=$template->getCreatedAt();?></td>
                        <td class="data"><?=$template->getUpdatedAt();?></td>
                    </tr>
                <?php
                    }
                }
                ?>
            </tbody>
        </table>
    </section>

    <!-- --------------------------- -->
    <!-- -------SECTION REVIEWS----- -->
    <!-- --------------------------- -->
    <section id="reviews" class="hidden">
        <h2>Panneau de control des reviews</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Sujet</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody id="reviews-body">
                <?php
                if($reviewManager->getReviewsOrderedByDate())
                {
                    $i = 0;
                    foreach($reviewManager->getReviewsOrderedByDate() as $review)
                    {   
                        $user = $userManager->getUserByUserId($review->getUserId());
                        $username = $user->getUsername();
                ?>
                    <tr>
                        <td class="data"><button class="row-btn" id="<?=$i;?>"><?=$i;?></button></td>
                        <td class="data"><?=$user->getUsername();?></td>
                        <td class="data"><?=$review->getSubject();?></td>
                        <td class="data"><?=$review->getSendDate();?></td>
                    </tr>
                <?php
                    $i++;
                    }
                }
                ?>
            </tbody>
        </table>
    </section>
    <section id="details" class="hidden"></section> <!-- Section gérer par le javascript -->
</main>
<script type="module" src="assets/js/dashboard.js"></script>