<nav class="navbar-foot">
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=login">Se connecter</a></li>
        <li><a href="index.php?route=register">Créer un compte</a></li>
    </ul>
</nav>
<nav class="contact-foot">
    <ul>
        <li><a><i class="fa-brands fa-github" style="color: #ff9651;"></i>Github</a></li>
        <li></li>
        <li></li>
    </ul>   
</nav>