<nav class="navbar-foot">
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=login">Se connecter</a></li>
        <li><a href="index.php?route=register">Créer un compte</a></li>
        <li><a href="index.php?route=about">À propos</a></li>
    </ul>
</nav>
<nav class="contact-foot">
    <ul>
        <li><a href="https://github.com/kodingcore" target="_blank"><i class="fa-brands fa-github" style="color: #ff9651;"></i>Github</a></li>
        <li><a href="https://linkedin.com/in/kodingcore" target="_blank"><i class="fa-brands fa-linkedin" style="color: #c55a11;"></i> LinkedIn</a></li>
        <a href="index.php?route=gnu">Politique de confidentialité</a>
    </ul>   
</nav>