
        <main id="about-container">
    <!-- --------------------------- -->
    <!-- -----HEADER-----HEADER----- -->
    <!-- --------------------------- -->
    <header id="main-header">
    </header>
    <!-- --------------------------- -->
    <h1>À propos de moi</h1>
    <section id="presentation">
        <h2>Présentation personnelle</h2>
        <p>Bonjour, je suis Kévin Corvaisier, fondateur de KodingCore Developpment. Passionné par la programmation informatique depuis mon plus jeune âge, j'ai consacré une grande partie de ma vie à créer des logiciels et des jeux vidéo. À l'âge de 30 ans, j'ai finalement décidé de faire de ma passion mon métier. Je suis un développeur web full-stack diplômé de la 3WA, formation pendant laquelle j'ai recréer un site Wordpress pour une naturopathe, afin d'amélioré son référencement, ainsi que l'experience utilisateur. Aujourd'hui, voici mon site professionnel, qui, à l'oposé de Wordpress, est codé uniquement en language natif, et m'as permis de mettre en pratique la vrai programmation. Ce site, qui comprends, des inscriptions, des avis clients, un dashbord et plus encore, offre des services de création de sites sur mesure grâce à un formulaire détaillé qui capture les besoins uniques de chaque client.</p>
    </section>

    <section id="objectifs">
        <h2>Motivation et Objectifs</h2>
        <p>Ma motivation découle de ma passion inébranlable pour la programmation. J'ai décidé de créer KodingCore Developpment avec l'objectif de fournir le service le plus efficace et fiable pour propulser vos projets vers un avenir toujours meilleur. Mon expérience en développement web, ma maîtrise des langages tels que HTML, CSS / SCSS, SQL, PHP et Javascript, ainsi que mon bagage en C# et d'autres langages, me permettent de créer des sites sur mesure et fiables.</p>
    </section>
    
    <section id="experience">
        <h2>Expérience</h2>
        <p>Mon parcours comprend près de cinq ans de développement de jeux vidéo sur Unity, suivi de quinze ans d'expérience approfondie en C#. J'ai également travaillé avec des langages tels que VisualBasic, Python, Ruby, ainsi que C et C++. Mon premier pas dans le monde de la programmation a été la création de mon premier jeu "Snake" en multijoueurs local à l'âge de 11 ans en utilisant C++. Ces expériences variées m'ont permis d'acquérir une expertise solide dans le domaine du développement web et logiciel, et je suis déterminé à mettre cette expertise au service de la réussite de vos projets avec KodingCore Developpment.</p>
    </section>
    
</main>