
<main id="gnu-container">
    <!-- --------------------------- -->
    <!-- -----HEADER-----HEADER----- -->
    <!-- --------------------------- -->
    <header id="main-header">
    </header>
    <!-- --------------------------- -->
    <h1>Politique de confidentialité</h1>
    <p>Kévin Corvaisier</p>
    <p>Type de site : Vitrine</p>
    <section id="but">
        <h2>Le but de cette politique de confidentialité</h2>
        <p>Le but de cette politique de confidentialité est d'informer les utilisateurs de notre site des données personnelles que nous recueillerons ainsi que les informations suivantes, le cas échéant :</p>
        <ul>
            <li>Les données personnelles que nous recueillerons</li>
            <li>L'utilisation des données recueillies</li>
            <li>Qui a accès aux données recueillies</li>
            <li>Les droits des utilisateurs du site</li>
            <li>La politique de cookies du site</li>
        </ul>
        <p>Cette politique de confidentialité fonctionne parallèlement aux conditions générales d'utilisation de notre site.</p>
    </section>
    
    <section id="lois">
        <h2>Lois applicables</h2>
        <p>Conformément au Règlement général sur la protection des données (RGPD), cette politique de confidentialité est conforme aux règlements suivants.</p>
        <p>Les données à caractère personnel doivent être :</p>
        <ul>
            <li>Traitées de manière licite, loyale et transparente au regard de la personne concernée (licéité, loyauté, transparence);</li>
            <li>Collectées pour des finalités déterminées, explicites et légitimes, et ne pas être traitées ultérieurement d'une manière incompatible avec ces finalités; le traitement ultérieur à des fins archivistiques dans l'intérêt public, à des fins de recherche scientifique ou historique ou à des fins statistiques n'est pas considéré, conformément à l'article 89, paragraphe 1, comme incompatible avec les finalités initiales (limitation des finalités);</li>
            <li>Adéquates, pertinentes et limitées à ce qui est nécessaire au regard des finalités pour lesquelles elles sont traitées (minimisation des données);</li>
            <li>Exactes et, si nécessaire, tenues à jour; toutes les mesures raisonnables doivent être prises pour que les données à caractère personnel qui sont inexactes, eu égard aux finalités pour lesquelles elles sont traitées, soient effacées ou rectifiées sans tarder (exactitude):</li>
            <li>Conservées sous une forme permettant l'identification des personnes concernées pendant une durée n'excédant pas celle nécessaire au regard des finalités pour lesquelles elles sont traitées; les données à caractère personnel peuvent être conservées pour des durées plus longues dans la mesure où elles seront traitées exclusivement à des fins archivistiques dans l'intérêt public, à des fins de recherche scientifique ou historique ou à des fins statistiques conformément à l'article 89, paragraphe 1, pour autant que soient mises en œuvre les mesures techniques et organisationnelles appropriées requises par le règlement afin de garantir les droits et libertés de la personne concernée (limitation de la conservation);</li>
            <li>Traitées de façon à garantir une sécurité appropriée des données à caractère personnel, y compris la protection contre le traitement non autorisé ou illicite et contre la perte, la destruction ou les dégâts d'origine accidentelle, à l'aide de mesures techniques ou organisationnelles appropriées (intégrité et confidentialité).</li>
        </ul>
        <p>Le traitement n'est licite que si, et dans la mesure où, au moins une des conditions suivantes est remplie :</p>
        <ul>
            <li>La personne concernée a consenti au traitement de ses données à caractère personnel pour une ou plusieurs finalités spécifiques</li>
            <li>Le traitement est nécessaire à l'exécution d'un contrat auquel la personne concernée est partie ou à l'exécution de mesures précontractuelles prises à la demande de celle-ci ;</li>
            <li>Le traitement est nécessaire au respect d'une obligation légale à laquelle le responsable du traitement est soumis ;</li>
            <li>Le traitement est nécessaire à la sauvegarde des intérêts vitaux de la personne concernée ou d'une autre personne physique ;</li>
            <li>Le traitement est nécessaire à l'exécution d'une mission d'intérêt public ou relevant de l'exercice de l'autorité publique dont est investi le responsable du traitement ;</li>
            <li>Le traitement est nécessaire aux fins des intérêts légitimes poursuivis par le responsable du traitement ou par un tiers, à moins que ne prévalent les intérêts ou les libertés et droits fondamentaux de la personne concernée qui exigent une protection des données à caractère personnel, notamment lorsque la personne concernée est un enfant.</li>
        </ul>
        <p>Pour les résidents de l'État de Californie, cette politique de confidentialité vise à se conformer à la California Consumer Privacy Act (CCPA). S'il y a des incohérences entre ce document et la CCPA, la législation de l'État s'appliquera. Si nous constatons des incohérences, nous modifierons notre politique pour nous conformer à la loi pertinente.</p>
    </section>
    
    <section id="consent">
        <h2>Consentement</h2>
        <p>Les utilisateurs conviennent qu'en utilisant notre site, ils consentent à :</p>
        <ul>
            <li>Les conditions énoncées dans la présente politique de confidentialité et</li>
            <li>La collecte, l'utilisation et la conservation des données énumérées dans la présente politique.</li>
        </ul>
    </section>
    
    <section id="collecte">
        <h2>Données personnelles que nous collectons</h2>
        <h3>Données collectées automatiquement</h3>
        <p>Nous ne collectons aucune donnée automatiquement sur notre site.</p>
        <h3>Données recueillies de façon non automatique</h3>
        <p>Nous pouvons également collecter les données suivantes lorsque vous effectuez certaines fonctions sur notre site:</p>
        <ul>
            <li>Prénom et nom</li>
            <li>Email</li>
            <li>Numéro de téléphone</li>
            <li>Domicile</li>
        </ul>
        <p>Ces données peuvent être recueillies au moyen des méthodes suivantes :</p>
        <p>Enregistrement d'un compte</p>
        <p>Veuillez noter que nous ne collectons que les données qui nous aident à atteindre l'objectif énoncé dans cette politique de confidentialité. Nous ne recueillerons pas de données supplémentaires sans vous en informer au préalable.</p>
    </section>
    
    <section id="utilisation">
        <h2>Comment nous utilisons les données personnelles</h2>
        <p>Les données personnelles recueillies sur notre site seront utilisées uniquement aux fins précisées dans la présente politique ou indiquées sur les pages pertinentes de notre site. Nous n'utiliserons pas vos données au-delà de ce que nous divulguerons.</p>
        <p>Les données que nous recueillons lorsque l'utilisateur exécute certaines fonctions peuvent être utilisées aux fins suivantes :</p>
        <ul>
            <li>Communication</li>
        </ul>
        <h3>Employés</h3>
        <p>Nous pouvons divulguer à tout membre de notre organisation les données utilisateur dont il a raisonnablement besoin pour réaliser les objectifs énoncés dans la présente politique.</p>
        <h3>Tierces parties</h3>
        <p>Nous ne partageons aucunes données utilisateur avec des tiers</p>
        <h3>Autres divulgations</h3>
        <p>Nous nous engageons à ne pas vendre ou partager vos données avec des tiers, sauf dans les cas suivants :</p>
        <ul>
            <li>Si la loi l'exige</li>
            <li>Si elle est requise pour toute procédure judiciaire</li>
            <li>Pour prouver ou protéger nos droits légaux</li>
            <li>À des acheteurs ou des acheteurs potentiels de cette société dans le cas où nous cherchons à la vendre la société</li>
        </ul>
        <p>Si vous suivez des hyperliens de notre site vers un autre site, veuillez noter que nous ne sommes pas responsables et n'avons pas de contrôle sur leurs politiques et pratiques de confidentialité.</p>
    </section>
    
    <section id="temps">
        <h2>Combien de temps nous stockons les données personnelles</h2>
        <p>Nous ne conservons pas les données des utilisateurs au-delà de ce qui est nécessaire pour atteindre les fins pour lesquelles elles sont recueillies. Dépassé un certain délais d'inactivité du compte, ce dernier sera supprimer de la base de données.</p>
    </section>
    
    <section id="protection">
        <h2>Comment nous protégeons vos données personnelles</h2>
        <p>Afin d'assurer la protection de votre sécurité, nous utilisons le protocole de sécurité de la couche transport pour transmettre des renseignements personnels dans notre système.</p>
        <p>Toutes les données stockées dans notre système sont bien sécurisées et ne sont accessibles qu'à nos employés. Nos employés sont liés par des accords de confidentialité stricts et une violation de cet accord entraînerait le licenciement de l'employé.</p>
        <p>Alors que nous prenons toutes les précautions raisonnables pour nous assurer que nos données d'utilisateur sont sécurisées et que les utilisateurs sont protégés, il reste toujours du risque de préjudice. L'Internet en sa totalité peut être, parfois, peu sûr et donc nous sommes incapables de garantir la sécurité des données des utilisateurs au-delà de ce qui est raisonnablement pratique.</p>
    </section>
        
    <section id="mineur">
        <h2>Mineurs</h2>
        <p>Le RGPD précise que les personnes de moins de 15 ans sont considérées comme des mineurs aux fins de la collecte de données. Les mineurs doivent avoir le consentement d'un représentant légal pour que leurs données soient recueillies, traitées et utilisées.</p>
    </section>
        
    <section id="droits">
        <h2>Vos droits en tant qu'utilisateur</h2>
        <p>En vertu du RGPD, les utilisateurs ont les droits suivants en tant que personnes concernées :</p>
        <ul>
            <li>Droit d'accès</li>
            <li>Droit de rectification</li>
            <li>Droit à l'effacement</li>
            <li>Droit de restreindre le traitement</li>
            <li>Droit à la portabilité des données</li>
            <li>Droit d'objection</li>
        </ul>
        <p>Vous trouverez de plus amples informations sur ces droits au chapitre 3 (art 12-23) du RGPD.</p>
    </section>
        
    <section id="edit-data">
        <h2>Comment modifier, supprimer ou contester les données recueillies</h2>
        <p>Si vous souhaitez que vos renseignements soient supprimés ou modifiés d'une façon ou d'une autre, veuillez communiquer avec notre agent de protection de la vie privée ici :</p>
        <p>06 31 31 83 58</p>
        <p>kodingcore@gmail.com</p>
        <p>1 lotissement du cèdre, 35420, le ferré</p>
    </section>
    
    <section id="edit-poli">
        <h2>Modifications</h2>
        <p>Cette politique de confidentialité peut être modifiée à l'occasion afin de maintenir la conformité avec la loi et de tenir compte de tout changement à notre processus de collecte de données. Nous recommandons à nos utilisateurs de vérifier notre politique de temps à autre pour s'assurer qu'ils soient informés de toute mise à jour. Au besoin, nous pouvons informer les utilisateurs par courriel des
        changements apportés à cette politique.</p>
    </section>
    
    <section id="contact">
        <h2>Contact</h2>
        <p>Si vous avez des questions à nous poser, n'hésitez pas à communiquer avec nous en utilisant ce qui suit :</p>
        <p>06 31 31 83 58</p>
        <p>kodingcore@gmail.com</p>
        <p>1 lotissement du cèdre, 35420, le ferré</p>
        <p>Date d'entrée en vigueur : le 21 septembre 2023</p>
        <p>©2023, KodingCore</p>
    </section>
    
    
    
    
    
    
    
    
</main>

<!-- ------------------------------------------------------------------------------------- -->
<!-- ------------------------PANNEAU GAUCHE LES ANCRES DE LA PAGE------------------------- -->
<!-- ------------------------------------------------------------------------------------- -->
<aside id="left-aside">
    <ul>
        <li><a href="#but">But</a></li>
        <li><a href="#lois">Lois</a></li>
        <li><a href="#consent">Consentement</a></li>
        <li><a href="#collecte">Collecte</a></li>
        <li><a href="#utilisation">Utilisation</a></li>
        <li><a href="#temps">Temps de stockage</a></li>
        <li><a href="#protection">Protection</a></li>
        <li><a href="#mineur">Mineurs</a></li>
        <li><a href="#droits">Droits</a></li>
        <li><a href="#edit-data">Édition data</a></li>
        <li><a href="#edit-poli">MAJ politique</a></li>
        <li><a href="#contact">Contact</a></li>
    </ul>
</aside>