<main id="login-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Bienvenue! Connectez-vous.
            </p>
        </div>
    </header>
    <h1>Connexion</h1>
    <?php
    if(isset($this->data["message"]) && $this->data["field"] === "general") //*Si on à un message dans la data
    {
        ?>
        <span class="success"><?=$this->data["message"]; ?></span>
        <?php
    }
    ?>
    <form action="index.php?route=login" method="POST" id="login_form">
        <fieldset>
            <label for="username_email">Username / Email</label>
            <input type="text" name="username_email" id="username_email" autocomplete="username" required maxlength="50" onpaste="return false;">
            <span id="error_username_email"<?php
                if(isset($this->data["message"]) && $this->data["field"] === "username_email")
                {
                    ?> class="content-write">
                    <?= $this->data["message"];
                }
            ?></span>
        </fieldset>
        <fieldset>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" autocomplete="current-password" required maxlength="50" onpaste="return false;">
            <span id="error_password"<?php
                if(isset($this->data["message"]) && $this->data["field"] === "password")
                {
                    ?> class="content-write">
                    <?= $this->data["message"];
                }
            ?></span>
        </fieldset>
        <input type="submit" value="Login">
    </form>
</main>