<?php
    if(isset($this->data["message"])) //*Si on à un message dans la data
    {
        ?>
        <span class="advert"><?=$this->data["message"]; ?></span>
        <?php
    }
?>
<form action="index.php?route=register" method="POST">
    <label for="username">Username</label>
    <input type="text" name="username" id="username" required maxlength="50" onpaste="return false;">

    <label for="email">Email</label>
    <input type="email" name="email" id="email" required maxlength="100" onpaste="return false;">

    <label for="password">Password</label>
    <input type="password" name="password" id="password" required minlength="8" maxlength="50" onpaste="return false;">

    <label for="confirm_password">Confirm password</label>
    <input type="password" name="confirm_password" id="confirm_password" required minlength="8" maxlength="50" onpaste="return false;">
    
    <input type="submit" value="Register">
</form>