<header class="lightmode" role="banner">
    <div id="logo-kc">
        <img src="https://i.goopics.net/cygi2i.png"  width="80" alt="">
    </div>
    <nav>
        <ul>
            <li><a href="index.php?route=">Homepage</a></li>
            <!-- <li><a href="#">Porte folio</a></li> -->
            <li><a href="index.php?route=login">Login</a></li>
            <li><a href="index.php?route=register">Register</a></li>
        </ul>
    </nav>
</header>