<?php
// Désactiver le cache
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Pragma: no-cache");
header("Expires: Sat, 26 Jul 1997 05:00:00 GMT");
?>

<main id="homepage-container">
    <!-- --------------------------- -->
    <!-- -----HEADER-----HEADER----- -->
    <!-- --------------------------- -->
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                "KodingCore, when your dreams are taking shape"
            </p>
        </div>
    </header>
    <!-- --------------------------- -->
    <!-- -----HEADER-----HEADER----- -->
    <!-- --------------------------- -->
    <h1>Accueil</h1>
    <?php
    if(isset($this->data["message"]) && $this->data["field"] === "general") //*Si on à un message dans la data
    {
        ?>
        <span class="success"><?=$this->data["message"]; ?></span>
        <?php
    }
    ?>
    <section id="presentation">
        <h2>Qui sommes nous?</h2>
        <p class="text-center">
            La passion pour la technologie et un engagement fort dans les domaines de l'informatique
            sont à la base de la création de "KodingCore Development" avec un objectif clair : fournir aux
            professionnels des solutions de Développement web et logiciel innovantes et sur mesure.
        </p>
    </section>
    <h2>Dernières créations</h2>
    <section id="templates-section">   
    <?php
    if(isset($this->data["templates"]))
    {
        $templates = $this->data["templates"];
        foreach ($templates as $key => $template) 
        {
    ?>
        <article class="template-card">
            <header>
                <h3><?= $template->getName(); ?></h3>
            </header>
                <img src="<?= $template->getImagePath() ?>" alt="Image du template <?= $template->getName() ?>">
            <footer>
                <p><?= $template->getDescription() ?></p>
                <p><?= $template->getCreatedAt() ?></p>
            </footer>
        </article>
    <?php
        }   
    }
    ?>
    </section>

    <h2>Avis clients</h2>
    <section id="reviews-section">
    <?php
    if(isset($this->data["reviews"]))
    {
        $reviews = $this->data["reviews"];
        foreach ($reviews as $key => $review) 
        {   
        ?>

        <article class="review-card">
        <?php
            if(isset($this->data["users"]))
            {
                $users = $this->data["users"];
                ?><p><?= $users[$key]->getUsername(); ?></p><?php
            }
            ?>
            <div class="review-notation">
            <?php
            for($i = 0; $i < 5; $i++)
            {
                
                if($i < $review->getNotation())
                {
                    ?><i class="fa-solid fa-star" style="color: #ff9651;"></i><?php
                }
                else
                {
                    ?><i class="fa-regular fa-star" style="color: #ff9651;"></i><?php
                }
                
            }
            ?>
            </div>
            <p><?= $review->getSendDate(); ?></p>
            <p><?= $review->getContent(); ?></p>
        </article>
        <?php
        }   
    }
    ?>
    </section>
    <?php
        if(isset($_SESSION["user_id"], $_SESSION["role"])) //* Control des variables de sessions pour l'acces users et admin
        {
            ?>
            <h2>Laissez un commentaire</h2>
            <section id="make-review-section">
            <form action="index.php?route=homepage-review-send" method="POST" id="review_form">
                <fieldset class="textarea">
                    <label for="content">Laissez un commentaire</label>
                    <textarea id="content" name="content" placeholder="Votre texte ici..." required minlength="10" maxlength="2048"></textarea>
                    <span id="error_content"
                    <?php
                    if(isset($this->data["message"]) && $this->data["field"] === "content")
                    {
                        ?> class="content-write">
                        <?= $this->data["message"];
                    }?>
                    </span>
                </fieldset>
                <div class="notation">
                    <i class="fa-regular fa-star" style="color: #ff9651;"></i>
                    <i class="fa-regular fa-star" style="color: #ff9651;"></i>
                    <i class="fa-regular fa-star" style="color: #ff9651;"></i>
                    <i class="fa-regular fa-star" style="color: #ff9651;"></i>
                    <i class="fa-regular fa-star" style="color: #ff9651;"></i>
                </div>
                <input type="hidden" name="rating" id="rating"/>
                <input type="submit" value="Envoyer"/>
            </form>
    </section> <?php
        }
    ?>
    
</main>
<script type="module" src="assets/js/notation.js"></script>
<!-- ------------------------------------------------------------------------------------- -->
<!-- ------------------------PANNEAU GAUCHE LES ANCRES DE LA PAGE------------------------- -->
<!-- ------------------------------------------------------------------------------------- -->
<aside id="left-aside">
    <ul>
        <li><a href="#presentation">Présentation</a></li>
        <li><a href="#templates-section">Dernières templates</a></li>
        <li><a href="#reviews-section">Avis-clients</a></li>
        <?php
        if(isset($_SESSION["user_id"], $_SESSION["role"])) //* Control des variables de sessions pour l'acces users et admin
        {
            ?>
                <li><a href="#make-review-section">Laissez un commentaire</a></li>
            <?php
        }
    ?>
    </ul>
</aside>

