<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Koding Core</title>
</head>
<body>
    <?php
    if(isset($_SESSION["user_id"]))
    {
        if(isset($_SESSION["role"]))
        {
            if($_SESSION["role"] === "admin")
            {
                require "views/roles-templates/admin/_header.phtml";
            }
            else if($_SESSION["role"] === "user")
            {
                require "views/roles-templates/user/connected/_header.phtml";
            }
            
        }
        else
        {
            require "views/roles-templates/user/connected/_header.phtml";
        }
        
    }
    else
    {
        require "views/roles-templates/user/guest/_header.phtml";
    }

        require $this->template;
    ?>
</body>
</html>