<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KodingCore Developpement</title>
    <link rel="icon" type="image/png" href="https://i.goopics.net/wovpgb.png">
    <link rel="stylesheet" href="assets/styles/css/style.css">
</head>
<body>
    <header>
        <div id="top-header">
            <div class="logo"></div>
        </div>
    </header>
    <nav>
        <?php
            if(isset($_SESSION["user_id"]) && isset($_SESSION["role"]))
            {
                if($_SESSION["role"] === "admin")
                {
                    require 'admin/_navlist.phtml';
                }
                else
                {
                    require 'user/_navlist.phtml';
                }   
            }
            else
            {
                require 'guest/_navlist.phtml';
            }
        ?>
    </nav>
    <main id="content">
        <section>
        <?php
            require $this->template;
        ?>
        </section>
    </main>
    <script type="module" src="assets/js/index.js"></script>
</body>
</html>