<header class="lightmode" role="banner">
    <div id="logo-kc">
        <img src="https://i.goopics.net/cygi2i.png" width="80" alt="">
    </div>
    <nav>
        <ul>
            <li><a href="index.php?route=">Homepage</a></li>
            <!-- <li><a href="#">Porte folio</a></li> -->
            <li><a href="index.php?route=shop-window">Shop window</a></li>
            <li><a href="index.php?route=account">My account</a></li>
            <li><a href="index.php?route=control-board">Control board</a></li>
            <li><a href="index.php?route=disconnect">Disconnect</a></li>
        </ul>
    </nav>
</header>