<nav class="navbar-foot">
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=shop">Vitrine</a></li>
        <li><a href="index.php?route=account">Mon compte</a></li>
        <li><a href="index.php?route=contact">Contactez moi</a></li>
        <li><a href="index.php?route=disconnect">Se déconnecter</a></li>
    </ul>
</nav>
<nav class="contact-foot">
    <ul>
        <li><a><i class="fa-brands fa-github" style="color: #ff9651;"></i>Github</a></li>
        <li></li>
        <li></li>
    </ul>   
</nav>