
<?php
    if(isset($this->data["message"])) //*Si on à un message dans la data
    {
        ?>
        <span class="success"><?=$this->data["message"]; ?></span>
        <?php
    }
?>
<main class="contact-container" id="contact-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Besoin d'aide où D'un renseignement? Une demande?
            </p>
        </div>
    </header>
    <h1>Envoyer un message à l'administrateur</h1>
    <form action="index.php?route=contact" method="POST" id="contact_form">
        <fieldset>
            <label for="subject">Sujet</label>
            <input type="text" name="subject" id="subject" autocomplete="off" required minlength="4" maxlength="50">
        </fieldset>
        <fieldset class="textarea">
            <label for="content">Message</label>
            <textarea id="content" name="content" placeholder="Votre texte ici..." required minlength="10" maxlength="2048"></textarea>
        </fieldset>
        <input type="submit" value="Envoyer">
    </form>
</main>