<main id="contact-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Besoin d'aide, d'un renseignement?
            </p>
        </div>
    </header>
    <h1>Envoyer un message</h1>
    <?php
    if(isset($this->data["message"]) && $this->data["field"] === "general") //*Si on à un message dans la data
    {
        ?>
        <span class="success"><?=$this->data["message"]; ?></span>
        <?php
    }
    ?>
    <form action="index.php?route=contact" method="POST" id="contact_form">
        <fieldset>
            <label for="subject">Sujet</label>
            <input type="text" name="subject" id="subject" placeholder="Votre sujet ici..." required minlength="4" maxlength="50">
            <span id="error_subject"
            <?php
            if(isset($this->data["message"]) && $this->data["field"] === "subject")
            {
                ?> class="content-write">
                <?= $this->data["message"];
            }?>
            </span>
        </fieldset>
        
        <fieldset class="textarea">
            <div class="input-separator"></div>
            <label for="content">Message</label>
            <textarea id="content" name="content" placeholder="Votre texte ici..." required minlength="10" maxlength="2048"></textarea>
            <span id="error_content"
            <?php
            if(isset($this->data["message"]) && $this->data["field"] === "content")
            {
                ?> class="content-write">
                <?= $this->data["message"];
            }?>
            </span>
        </fieldset>
        <input type="submit" value="Envoyer">
    </form>
    
    <script type="module" src="assets/js/checkMessageFields.js"></script>
</main>