<main>
    <section>
        <?php
            if(isset($this->data["message"])) //Si l'on à un message dans la data
            {
                ?>
                <span class="advert"><?=$this->data["message"]; ?></span> <?php //On affiche le message ?>
                <?php
            }
        ?>
        <form action="index.php?route=login" method="POST"> <?php //Formulaire de login ?>
            <label for="username-email">Username / Email</label>
            <input type="text" name="username-email" id="username-email" required>
            <label for="password">Password</label> 
            <input type="password" name="password" id="password" requires>
            <input type="submit" value="Log In">
        </form>
    </section>
</main>    