<main>
    <form action="index.php?route=register" method="POST"> //Formulaire d'inscription
        <label for="username">Username</label>
        <input type="text" name="username" id="username">
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
        <label for="password">Password</label>
        <input type="password" name="password" id="password">
        <label for="confirm-password">Confirm password</label>
        <input type="password" name="confirm-password" id="confirm-password">
        <input type="submit" value="Register">
    </form>
</main>