<main id="request-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Commençez votre projet
            </p>
        </div>
    </header>
    <h1>Demandez votre site sur-mesure</h1>
    <?php
    if(isset($this->data["message"]) && $this->data["field"] === "general") //*Si on à un message dans la data
    {
        ?>
        <span class="success"><?=$this->data["message"]; ?></span>
        <?php
    }
    ?>
    <h2>Nos créations comprennent toutes les fonctionnalitées suivantes de base:</h2>
    <ul>
        <li>Compatibilité des navigateurs</li>
        <li>Optimisation du SEO, du référencement</li>
        <li>Compression des images et éco-conception</li>
        <li>Optimisation des performances et minimisation</li>
        <li>Sécurisation des données et des actions malveillantes</li>
        <li>Interface et Expérience Utilisateur (UI et UX) optimisées</li>
    </ul>
    <p>Le formulaire suivant permet une approche plus précise de ce que vous attendez de notre service.</p>
    <p>La relation client que nous offront, affienera votre demande, pour vous offrir un site web sur mesure.</p>
    <form action="index.php?route=add-request" method="POST" id="request_form">
        <h2>Formulaire de demande</h2>
        <fieldset>
            <legend>Catégorie du site web :</legend>
            <label for="category">Catégorie</label>
            <select name="category" id="category">
                <?php

                if(isset($this->data["categories"]))
                {
                    $categories = $this->data["categories"];
                    foreach ($categories as $category) 
                    {
                        ?>
                            <option value="<?=$category->getCategoryId();?>"><?=$category->getName();?></option>
                        <?php
                    }
                }

                ?>
            </select>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Fonctionnalités de base :</legend>

            <label for="cms">Utilisation d'un système de gestion de contenu (CMS)</label>
            <input type="checkbox" name="cms" id="cms">
            <span class="input-description">Réduis la personnalisation et les possibilitées fonctionnelles. Ainsi que le coût!</span>

            <div class="input-separator"></div>

            <label for="suscribe">Inscription et gestion des utilisateurs</label>
            <input type="checkbox" name="suscribing" id="suscribing">
            <span class="input-description">Création de comptes, connexion, gestion de profils.</span>

            <div class="input-separator"></div>

            <label for="reviews">Commentaires</label>
            <input type="checkbox" name="reviews" id="reviews">
            <span class="input-description">Possibilité de laisser des commentaires sur le contenu.</span>

            <div class="input-separator"></div>

            <label for="research">Recherche</label>
            <input type="checkbox" name="research" id="research">
            <span class="input-description">Fonction de recherche pour trouver rapidement du contenu.</span>

            <div class="input-separator"></div>

            <label for="social">Partage sur les médias sociaux</label>
            <input type="checkbox" name="social" id="social">
            <span class="input-description">Permet aux utilisateurs de partager du contenu sur les réseaux sociaux.</span>

            <div class="input-separator"></div>

            <label for="localisation">Géolocalisation</label>
            <input type="checkbox" name="localisation" id="localisation">
            <span class="input-description">Intégration de cartes pour afficher des emplacements.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Fonctionnalités e-commerce :</legend>

            <label for="products-gestion">Gestion des produits</label>
            <input type="checkbox" name="products" id="products">
            <span class="input-description">Ajout, édition et suppression de produits.</span>

            <div class="input-separator"></div>

            <label for="kart">Panier d'achat</label>
            <input type="checkbox" name="kart" id="kart">
            <span class="input-description">Fonctionnalité de panier pour les achats en ligne.</span>

            <div class="input-separator"></div>

            <label for="paylink">Paiement en ligne</label>
            <input type="checkbox" name="paylink" id="paylink">
            <span class="input-description">Intégration de passerelles de paiement pour les transactions.</span>

            <div class="input-separator"></div>

            <label for="auto-quotation">Facturation</label>
            <input type="checkbox" name="auto-quotation" id="auto-quotation">
            <span class="input-description">Génération automatique de factures pour les commandes.</span>

            <div class="input-separator"></div>

            <label for="notation">Système de notation</label>
            <input type="checkbox" name="notation" id="notation">
            <span class="input-description">Permet aux utilisateurs de noter et de commenter les produits.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Sites de discussion et de communauté :</legend>

            <label for="talking-forum">Forums et discussions</label>
            <input type="checkbox" name="talking-forum" id="talking-forum">
            <span class="input-description">Création de forums, discussion de sujets.</span>

            <div class="input-separator"></div>

            <label for="messaging">Messagerie</label>
            <input type="checkbox" name="messaging" id="messaging">
            <span class="input-description">Possibilité d'envoyer des messages et des notifications.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Sites de réservation et de services :</legend>

            <label for="reservation">Système de réservation</label>
            <input type="checkbox" name="reservation" id="reservation">
            <span class="input-description">Réservation de rendez-vous, services, etc.</span>

            <div class="input-separator"></div>

            <label for="calendar">Calendrier</label>
            <input type="checkbox" name="calendar" id="calendar">
            <span class="input-description">Affichage des disponibilités et des horaires.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Sites de médias et de divertissement :</legend>

            <label for="video-integration">Intégration de vidéos</label>
            <input type="checkbox" name="video-integration" id="video-integration">
            <span class="input-description">Diffusion de vidéos en direct ou à la demande.</span>

            <div class="input-separator"></div>

            <label for="media-reviews">Système de notation et de commentaires</label>
            <input type="checkbox" name="media-reviews" id="media-reviews">
            <span class="input-description">Notation et commentaires sur les médias.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox_field">
            <legend>Sites d'entreprise et professionnels :</legend>

            <label for="admin_dashboard">Tableau de bord administrateur</label>
            <input type="checkbox" name="admin-dashboard" id="admin_dashboard">
            <span class="input-description">Interface pour gérer les utilisateurs, le contenu, etc.</span>

            <div class="input-separator"></div>

            <label for="notification">Système de notifications</label>
            <input type="checkbox" name="notification" id="notification">
            <span class="input-description">Envoi de notifications par e-mail ou messages aux utilisateurs.</span>

            <div class="input-separator"></div>

            <label for="language">Multilinguisme</label>
            <input type="checkbox" name="language" id="language">
            <span class="input-description">Prise en charge de plusieurs langues pour un public international.</span>
        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="checkbox-field">
            <legend>Fonctionnalités de Design :</legend>

            <label for="responsive-design">Design responsive</label>
            <input type="checkbox" name="responsive-design" id="responsive-design">
            <span class="input-description">Assure que le site s'adapte correctement à tous les types d'appareils.</span>

            <div class="input-separator"></div>
            <label for="content-transmition">Transmition du contenu</label>
            <select name="content-transmition" id="content-transmition">
                <option value="no">Contenu inexistant</option>
                <option value="partial">Contenu partiel</option>
                <option value="complete">Contenu complet</option>
            </select>
            <span class="input-description">Le contenu de création (logos, images, vidéos, etc.) qui sera transmis à pour le développement</span>

            <div class="input-separator"></div>

        </fieldset>

        <div class="fieldset-separator"></div>

        <fieldset class="textarea">
            <legend>Description et précisions importantes du projet</legend>
            <label for="description">Description et précisions</label>
            <textarea id="description" name="description" placeholder="Votre texte ici..." required minlength="10" maxlength="2048"></textarea>
        </fieldset>
        <input type="submit" value="Envoyer">
    </form>
</main>