<main id="shop-container" class="shop-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Ici, c'est la vitrine. Consultez les templates!
            </p>
        </div>
    </header>
    <h1>Vitrine</h1>
    <section id="templates-section">
    <?php
    if(isset($this->data["templates"]) && isset($this->data["categories"]))
    {
        $templates = $this->data["templates"];
        $categories = $this->data["categories"];
        foreach($categories as $category)
        {
            $category_name = $category->getName();
            ?>
            <section id="<?=$category_name?>-section">
                <?php
                foreach($templates as $template)
                {
                    if($template->getCategoryId() === $category->getCategoryId())
                    {
                        ?>
                        <article class="cards">
                            <h3><?=$template->getName();?></h3>
                            <img width="250" src="<?=$template->getImagePath();?>" alt="Image du template proposé">
                            <p><?=$template->getDescription();?></p>
                            <a href="index.php?route=quote-request&id=<?=$template->getTemplateId();?>"><button class="btn">Demander un devis</button></a>
                        </article>
                        <?php
                    }
                }
                ?>
            </section>
            <?php
        }
    }
    ?>
</section>

</main>
<aside id="left-aside">
    <ul>
        <li><a href="#presentation">Présentation</a></li>
        <li><a href="#news">Nouveautés</a></li>
        <li><a href="#reviews">Avis-clients</a></li>
    </ul>
</aside>
