<main id="shop-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Ici, c'est la vitrine. Consultez les templates!
            </p>
        </div>
    </header>
    <h1>Vitrine</h1>
    <section id="templates-section">
        <p class="text-center">Voici une présentation des templates déjà créer par nos services. Celà peut vous donner une idée de ce que nous créont visuellement.</p>
    <?php
    if(isset($this->data["templates"]))
    {
        $templates = $this->data["templates"];
        foreach($templates as $template)
        {
            ?>
            <article class="template-card">
                <header>
                    <h3><?= $template->getName(); ?></h3>
                </header>
                    <img src="<?= $template->getImagePath() ?>" alt="Image du template <?= $template->getName() ?>">
                <footer>
                    <p><?= $template->getDescription() ?></p>
                    <p><?= "Créer le : {$template->getCreatedAt()}" ?></p>
                    <a href="index.php?route=request"><button class="btn">Votre site sur-mesure</button></a>
                </footer>
            </article>
            <?php
        }
    }
    ?>
</section>

</main>
<aside id="left-aside">
    <ul>
        <li><a href="#presentation">Présentation</a></li>
        <li><a href="#templates-section">Nouveautés</a></li>
        <li><a href="#reviews">Avis-clients</a></li>
    </ul>
</aside>
<script type="module" src="assets/js/shopClassesAttribution.js"></script>