<main id="shop-container" class="shop-container">
    <header id="main-header">
        <div id="tagline-container">
            <p id="tagline">
                Ici, c'est la vitrine. Consultez les templates!
            </p>
        </div>
    </header>
    <h1>Vitrine</h1>
    <section id="templates-section">
    <?php
    if(isset($this->data["templates"]) && isset($this->data["categories"]))
    {
        $templates = $this->data["templates"];
        $categories = $this->data["categories"];
        foreach($categories as $category)
        {
            $category_name = $category->getName();
            ?>
            <h2><?=$category_name?></h2>
            <section id="section-<?=$category_name?>-section">
                
                <?php
                foreach($templates as $template)
                {
                    if($template->getCategoryId() === $category->getCategoryId())
                    {
                        ?>
                        <article class="template-card">
                            <header>
                                <h3><?= $template->getName(); ?></h3>
                            </header>
                                <img src="<?= $template->getImagePath() ?>" alt="Image du template <?= $template->getName() ?>">
                            <footer>
                                <p><?= $template->getDescription() ?></p>
                                <p><?= $template->getCreatedAt() ?></p>
                                <a href="index.php?route=quote-request&template_id=<?=$template->getTemplateId();?>"><button class="btn">Demander un devis</button></a>
                            </footer>
                        </article>
                        <?php
                    }
                }
                ?>
            </section>
            <?php
        }
    }
    ?>
</section>

</main>
<aside id="left-aside">
    <ul>
        <li><a href="#presentation">Présentation</a></li>
        <li><a href="#templates-section">Nouveautés</a></li>
        <li><a href="#reviews">Avis-clients</a></li>
    </ul>
</aside>
